# Generated by Django 2.2.2 on 2019-07-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0002_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Name',
            new_name='Enter_Name',
        ),
        migrations.AddField(
            model_name='data',
            name='Securitycode',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='Score',
            field=models.IntegerField(default=0),
        ),
    ]
