# Generated by Django 2.2.2 on 2019-07-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0003_auto_20190715_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='email',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
