# Generated by Django 2.2.2 on 2019-07-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0004_data_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='email',
            new_name='Email_Address',
        ),
    ]
