# Generated by Django 2.2.2 on 2019-07-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0005_auto_20190715_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Email_Address',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
