# Generated by Django 2.2.2 on 2019-07-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0006_auto_20190715_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Email_Address',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
