# Generated by Django 2.2.2 on 2019-07-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0009_auto_20190715_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Email_Address',
            field=models.EmailField(max_length=254),
        ),
    ]
